package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const example = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

func TestMain(t *testing.T) {
	grid, err := getGrid(example)
	assert.Nil(t, err)
	assert.Equal(t, 14, len(part1(grid)))
	assert.Equal(t, 34, len(part2(grid)))
}
